name: GO Tests

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get .

      - name: Test with race enabled
        run: go test -v -cover -race ./... | tee test.log

      - uses: actions/upload-artifact@v3
        with:
          name: tpser-test-logs
          path: ./test.log
          retention-days: 3

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      run: go get .

    - name: Test for race condition
      run: go build -v -race -o tpser .

    - name: Build
      run: CGO_ENABLED=0 go build -v -o tpser .

    - uses: actions/upload-artifact@v3
      with:
        name: tpser-linux-binary
        path: ./tpser
        retention-days: 3